### PR TITLE
feature: add memory numa info

### PR DESCRIPTION
**Pull request by justadogistaken**
add memory numa info for supporting memory numa-aware scheduling. The major additions are same as definition of  kubernetes mostly.

### CODE REVIEW

**Review by shinytang6 — COMMENTED** [review]
That's great, I am also interested in that feature, can you give me some reference so that l can scan quickly and help review this feature?

**Comment by justadogistaken** [comment]
> That's great, I am also interested in that feature, can you give me some reference so that l can scan quickly and help review this feature?

Sure. I also think that I need to give more discriptions. I will supplement some references.

**Comment by justadogistaken** [comment]
The related issues are: https://github.com/volcano-sh/volcano/issues/1865 / https://github.com/volcano-sh/volcano/issues/1749

Kubelet will write numa memory topology to `/var/lib/kubelet/memory_manager_state`.
Those topology info will be used to calculate memory TopolofyHints. ref: https://github.com/kubernetes/kubernetes/blob/03bcfab1a6675563672ddc11bd24c613967b102c/pkg/kubelet/cm/memorymanager/policy_static.go#L426
(The info would be like):
```
{
   "policyName":"Static",
   "machineState":{
      "0":{
         "numberOfAssignments":1,
         "memoryMap":{
            "hugepages-1Gi":{
               "total":0,
               "systemReserved":0,
               "allocatable":0,
               "reserved":0,
               "free":0
            },
            "memory":{
               "total":134987354112,
               "systemReserved":3221225472,
               "allocatable":131766128640,
               "reserved":131766128640,
               "free":0
            }
         },
         "nodes":[
            0,
            1
         ]
      },
      "1":{
         "numberOfAssignments":1,
         "memoryMap":{
            "hugepages-1Gi":{
               "total":0,
               "systemReserved":0,
               "allocatable":0,
               "reserved":0,
               "free":0
            },
            "memory":{
               "total":135286722560,
               "systemReserved":2252341248,
               "allocatable":133034381312,
               "reserved":29295144960,
               "free":103739236352
            }
         },
         "nodes":[
            0,
            1
         ]
      }
   }
}
```

**Comment by Thor-wl** [comment]
It's generally OK to me. 
/lgtm

**Comment by justadogistaken** [comment]
@Thor-wl I think we'd better revert the pr https://github.com/volcano-sh/apis/pull/62 first. I need to re-learn this work. And I will finish the whole work first, after than commit corresponding prs.

**Pull request merged**
